name: Hexo Auto-Deploy
on: [push]

jobs:
  build:
    name: Hexo Auto-Deploy by GitHub Actions
    runs-on: ubuntu-latest

    steps:
      - name: 1. git checkout...
        uses: actions/checkout@v1

      - name: 2. setup nodejs...
        uses: actions/setup-node@v1

      - name: 3. install hexo...
        run: |
          export TZ='Asia/Shanghai'
          npm install hexo-cli -g
          npm install

      - name: 4. git settings
        run: |
          git config --global user.name "mirari"
          git config --global user.email "clover4@gmail.com"

      - name: 5. hexo deploy
        env:
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        run: |
          sed -i "s/gh_token/${ACCESS_TOKEN}/g" ./_config.yml
          hexo clean
          hexo g
          hexo deploy
