name: Hexo Auto-Deploy
on: [push]

jobs:
  build:
    name: Hexo Auto-Deploy by GitHub Actions
    runs-on: ubuntu-latest

    steps:
      - name: 1. git checkout...
        uses: actions/checkout@v1

      - name: 2. setup nodejs...
        uses: actions/setup-node@v1

      - name: 3. install hexo...
        run: |
          export TZ='Asia/Shanghai'
          npm install hexo-cli -g
          npm install

      - name: 4. git settings
        env:
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACCESS_TOKEN" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "mirari"
          git config --global user.email "clover4@gmail.com"

      - name: 5. hexo generate public files...
        run: |
          hexo clean
          hexo g
          hexo deploy
          rm ~/.ssh/id_rsa
